/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnfragenRouteImport } from './routes/anfragen'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as ErsatzteileRouteImport } from './routes/ersatzteile'
import { Route as FilamenteRouteImport } from './routes/filamente'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as KalkulatorRouteImport } from './routes/kalkulator'
import { Route as KleinserienRouteImport } from './routes/kleinserien'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeinKontoRouteImport } from './routes/mein-konto'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProfilErgaenzenRouteImport } from './routes/profil-ergaenzen'
import { Route as ProfilVervollstaendigenRouteImport } from './routes/profil-vervollstaendigen'
import { Route as PrototypenRouteImport } from './routes/prototypen'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as TeileRouteImport } from './routes/teile'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as WebsiteAdminRouteImport } from './routes/website-admin'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as Site3dDruckBernRouteImport } from './routes/_site/3d-druck-bern'
import { Route as Site3dDruckOstschweizRouteImport } from './routes/_site/3d-druck-ostschweiz'
import { Route as Site3dDruckStGallenRouteImport } from './routes/_site/3d-druck-st-gallen'
import { Route as Site3dDruckWinterthurRouteImport } from './routes/_site/3d-druck-winterthur'
import { Route as Site3dDruckZuerichRouteImport } from './routes/_site/3d-druck-zuerich'
import { Route as SiteAgbRouteImport } from './routes/_site/agb'
import { Route as SiteDatenschutzRouteImport } from './routes/_site/datenschutz'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SiteImpressumRouteImport } from './routes/_site/impressum'
import { Route as SiteKalkulatorOnlineRouteImport } from './routes/_site/kalkulator-online'
import { Route as SiteKontaktRouteImport } from './routes/_site/kontakt'
import { Route as SiteMaschinenRouteImport } from './routes/_site/maschinen'
import { Route as SiteUeberKiRouteImport } from './routes/_site/ueber-ki'
import { Route as SiteUeberUnsRouteImport } from './routes/_site/ueber-uns'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnfragenRouteImport } from './routes/admin/anfragen'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminDruckplattenRouteImport } from './routes/admin/druckplatten'
import { Route as AdminEinstellungenRouteImport } from './routes/admin/einstellungen'
import { Route as AdminFilamenteRouteImport } from './routes/admin/filamente'
import { Route as AdminKalenderRouteImport } from './routes/admin/kalender'
import { Route as AdminKalkulatorRouteImport } from './routes/admin/kalkulator'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminTeileRouteImport } from './routes/admin/teile'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AuftraegeIndexRouteImport } from './routes/auftraege.index'
import { Route as AuftraegeIdRouteImport } from './routes/auftraege.$id'
import { Route as BewertungIndexRouteImport } from './routes/bewertung.index'
import { Route as BewertungTokenRouteImport } from './routes/bewertung.$token'
import { Route as KundenIndexRouteImport } from './routes/kunden.index'
import { Route as KundenIdRouteImport } from './routes/kunden.$id'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalBestellungenRouteImport } from './routes/portal/bestellungen'
import { Route as PortalDokumenteRouteImport } from './routes/portal/dokumente'
import { Route as PortalPasswortRouteImport } from './routes/portal/passwort'
import { Route as PortalProfilRouteImport } from './routes/portal/profil'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as WebsiteAdminIndexRouteImport } from './routes/website-admin/index'
import { Route as WebsiteAdminAnalyseRouteImport } from './routes/website-admin/analyse'
import { Route as WebsiteAdminBlogRouteImport } from './routes/website-admin/blog'
import { Route as WebsiteAdminChatRouteImport } from './routes/website-admin/chat'
import { Route as WebsiteAdminEinstellungenRouteImport } from './routes/website-admin/einstellungen'
import { Route as WebsiteAdminEquipmentRouteImport } from './routes/website-admin/equipment'
import { Route as WebsiteAdminKundenRouteImport } from './routes/website-admin/kunden'
import { Route as WebsiteAdminNavigationRouteImport } from './routes/website-admin/navigation'
import { Route as WebsiteAdminPartnerRouteImport } from './routes/website-admin/partner'
import { Route as WebsiteAdminProjekteRouteImport } from './routes/website-admin/projekte'
import { Route as WebsiteAdminReviewsRouteImport } from './routes/website-admin/reviews'
import { Route as WebsiteAdminShopRouteImport } from './routes/website-admin/shop'
import { Route as WebsiteAdminShopProdukteRouteImport } from './routes/website-admin/shop-produkte'
import { Route as WebsiteAdminTeamRouteImport } from './routes/website-admin/team'
import { Route as WebsiteAdminTimelineRouteImport } from './routes/website-admin/timeline'
import { Route as WebsiteSplatRouteImport } from './routes/website.$'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog.$slug'
import { Route as SiteLeistungenIndexRouteImport } from './routes/_site/leistungen.index'
import { Route as SiteLeistungenSlugRouteImport } from './routes/_site/leistungen.$slug'
import { Route as SiteMaterialienIndexRouteImport } from './routes/_site/materialien.index'
import { Route as SiteMaterialienSlugRouteImport } from './routes/_site/materialien.$slug'
import { Route as SiteNewsletterAbmeldenRouteImport } from './routes/_site/newsletter.abmelden'
import { Route as SiteProjekteSlugRouteImport } from './routes/_site/projekte.$slug'
import { Route as SiteShopIndexRouteImport } from './routes/_site/shop.index'
import { Route as SiteShopSlugRouteImport } from './routes/_site/shop.$slug'
import { Route as SiteStandorteSlugRouteImport } from './routes/_site/standorte.$slug'
import { Route as SiteVergleichIndexRouteImport } from './routes/_site/vergleich.index'
import { Route as SiteVergleichSlugRouteImport } from './routes/_site/vergleich.$slug'
import { Route as SiteWissen3dDruckKostenSchweizRouteImport } from './routes/_site/wissen.3d-druck-kosten-schweiz'
import { Route as AdminAuftraegeIndexRouteImport } from './routes/admin/auftraege.index'
import { Route as AdminFinanzenIndexRouteImport } from './routes/admin/finanzen.index'
import { Route as AdminFinanzenNeueRechnungRouteImport } from './routes/admin/finanzen.neue-rechnung'
import { Route as AdminKundenIndexRouteImport } from './routes/admin/kunden.index'
import { Route as AdminKundenIdRouteImport } from './routes/admin/kunden.$id'
import { Route as AdminWebsiteBestellungenRouteImport } from './routes/admin/website.bestellungen'
import { Route as AdminWebsiteEinstellungenRouteImport } from './routes/admin/website.einstellungen'
import { Route as AdminWebsiteKundenRouteImport } from './routes/admin/website.kunden'
import { Route as WebsiteAdminBestellungenIndexRouteImport } from './routes/website-admin/bestellungen.index'
import { Route as WebsiteAdminBestellungenIdRouteImport } from './routes/website-admin/bestellungen.$id'
import { Route as AdminAuftraegeIdIndexRouteImport } from './routes/admin/auftraege.$id.index'
import { Route as AdminAuftraegeIdPlattenRouteImport } from './routes/admin/auftraege.$id.platten'
import { Route as AdminFinanzenAbrechnungenIndexRouteImport } from './routes/admin/finanzen.abrechnungen.index'
import { Route as AdminFinanzenAbrechnungenIdRouteImport } from './routes/admin/finanzen.abrechnungen.$id'
import { Route as AdminShopBestellungenIdRouteImport } from './routes/admin/shop.bestellungen.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfragenRoute = AnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ErsatzteileRoute = ErsatzteileRouteImport.update({
  id: '/ersatzteile',
  path: '/ersatzteile',
  getParentRoute: () => rootRouteImport,
} as any)
const FilamenteRoute = FilamenteRouteImport.update({
  id: '/filamente',
  path: '/filamente',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorRoute = KalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const KleinserienRoute = KleinserienRouteImport.update({
  id: '/kleinserien',
  path: '/kleinserien',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeinKontoRoute = MeinKontoRouteImport.update({
  id: '/mein-konto',
  path: '/mein-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilErgaenzenRoute = ProfilErgaenzenRouteImport.update({
  id: '/profil-ergaenzen',
  path: '/profil-ergaenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilVervollstaendigenRoute = ProfilVervollstaendigenRouteImport.update({
  id: '/profil-vervollstaendigen',
  path: '/profil-vervollstaendigen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypenRoute = PrototypenRouteImport.update({
  id: '/prototypen',
  path: '/prototypen',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const TeileRoute = TeileRouteImport.update({
  id: '/teile',
  path: '/teile',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAdminRoute = WebsiteAdminRouteImport.update({
  id: '/website-admin',
  path: '/website-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const Site3dDruckBernRoute = Site3dDruckBernRouteImport.update({
  id: '/3d-druck-bern',
  path: '/3d-druck-bern',
  getParentRoute: () => SiteRoute,
} as any)
const Site3dDruckOstschweizRoute = Site3dDruckOstschweizRouteImport.update({
  id: '/3d-druck-ostschweiz',
  path: '/3d-druck-ostschweiz',
  getParentRoute: () => SiteRoute,
} as any)
const Site3dDruckStGallenRoute = Site3dDruckStGallenRouteImport.update({
  id: '/3d-druck-st-gallen',
  path: '/3d-druck-st-gallen',
  getParentRoute: () => SiteRoute,
} as any)
const Site3dDruckWinterthurRoute = Site3dDruckWinterthurRouteImport.update({
  id: '/3d-druck-winterthur',
  path: '/3d-druck-winterthur',
  getParentRoute: () => SiteRoute,
} as any)
const Site3dDruckZuerichRoute = Site3dDruckZuerichRouteImport.update({
  id: '/3d-druck-zuerich',
  path: '/3d-druck-zuerich',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAgbRoute = SiteAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDatenschutzRoute = SiteDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteImpressumRoute = SiteImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKalkulatorOnlineRoute = SiteKalkulatorOnlineRouteImport.update({
  id: '/kalkulator-online',
  path: '/kalkulator-online',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKontaktRoute = SiteKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMaschinenRoute = SiteMaschinenRouteImport.update({
  id: '/maschinen',
  path: '/maschinen',
  getParentRoute: () => SiteRoute,
} as any)
const SiteUeberKiRoute = SiteUeberKiRouteImport.update({
  id: '/ueber-ki',
  path: '/ueber-ki',
  getParentRoute: () => SiteRoute,
} as any)
const SiteUeberUnsRoute = SiteUeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnfragenRoute = AdminAnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDruckplattenRoute = AdminDruckplattenRouteImport.update({
  id: '/druckplatten',
  path: '/druckplatten',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEinstellungenRoute = AdminEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilamenteRoute = AdminFilamenteRouteImport.update({
  id: '/filamente',
  path: '/filamente',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKalenderRoute = AdminKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKalkulatorRoute = AdminKalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeileRoute = AdminTeileRouteImport.update({
  id: '/teile',
  path: '/teile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuftraegeIndexRoute = AuftraegeIndexRouteImport.update({
  id: '/auftraege/',
  path: '/auftraege/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuftraegeIdRoute = AuftraegeIdRouteImport.update({
  id: '/auftraege/$id',
  path: '/auftraege/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BewertungIndexRoute = BewertungIndexRouteImport.update({
  id: '/bewertung/',
  path: '/bewertung/',
  getParentRoute: () => rootRouteImport,
} as any)
const BewertungTokenRoute = BewertungTokenRouteImport.update({
  id: '/bewertung/$token',
  path: '/bewertung/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenIndexRoute = KundenIndexRouteImport.update({
  id: '/kunden/',
  path: '/kunden/',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenIdRoute = KundenIdRouteImport.update({
  id: '/kunden/$id',
  path: '/kunden/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBestellungenRoute = PortalBestellungenRouteImport.update({
  id: '/bestellungen',
  path: '/bestellungen',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDokumenteRoute = PortalDokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPasswortRoute = PortalPasswortRouteImport.update({
  id: '/passwort',
  path: '/passwort',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfilRoute = PortalProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PortalRoute,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAdminIndexRoute = WebsiteAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminAnalyseRoute = WebsiteAdminAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminBlogRoute = WebsiteAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminChatRoute = WebsiteAdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminEinstellungenRoute =
  WebsiteAdminEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => WebsiteAdminRoute,
  } as any)
const WebsiteAdminEquipmentRoute = WebsiteAdminEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminKundenRoute = WebsiteAdminKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminNavigationRoute = WebsiteAdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminPartnerRoute = WebsiteAdminPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminProjekteRoute = WebsiteAdminProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminReviewsRoute = WebsiteAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminShopRoute = WebsiteAdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminShopProdukteRoute =
  WebsiteAdminShopProdukteRouteImport.update({
    id: '/shop-produkte',
    path: '/shop-produkte',
    getParentRoute: () => WebsiteAdminRoute,
  } as any)
const WebsiteAdminTeamRoute = WebsiteAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteAdminTimelineRoute = WebsiteAdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => WebsiteAdminRoute,
} as any)
const WebsiteSplatRoute = WebsiteSplatRouteImport.update({
  id: '/website/$',
  path: '/website/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLeistungenIndexRoute = SiteLeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLeistungenSlugRoute = SiteLeistungenSlugRouteImport.update({
  id: '/leistungen/$slug',
  path: '/leistungen/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMaterialienIndexRoute = SiteMaterialienIndexRouteImport.update({
  id: '/materialien/',
  path: '/materialien/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMaterialienSlugRoute = SiteMaterialienSlugRouteImport.update({
  id: '/materialien/$slug',
  path: '/materialien/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewsletterAbmeldenRoute = SiteNewsletterAbmeldenRouteImport.update({
  id: '/newsletter/abmelden',
  path: '/newsletter/abmelden',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjekteSlugRoute = SiteProjekteSlugRouteImport.update({
  id: '/projekte/$slug',
  path: '/projekte/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopIndexRoute = SiteShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopSlugRoute = SiteShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStandorteSlugRoute = SiteStandorteSlugRouteImport.update({
  id: '/standorte/$slug',
  path: '/standorte/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVergleichIndexRoute = SiteVergleichIndexRouteImport.update({
  id: '/vergleich/',
  path: '/vergleich/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVergleichSlugRoute = SiteVergleichSlugRouteImport.update({
  id: '/vergleich/$slug',
  path: '/vergleich/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWissen3dDruckKostenSchweizRoute =
  SiteWissen3dDruckKostenSchweizRouteImport.update({
    id: '/wissen/3d-druck-kosten-schweiz',
    path: '/wissen/3d-druck-kosten-schweiz',
    getParentRoute: () => SiteRoute,
  } as any)
const AdminAuftraegeIndexRoute = AdminAuftraegeIndexRouteImport.update({
  id: '/auftraege/',
  path: '/auftraege/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzenIndexRoute = AdminFinanzenIndexRouteImport.update({
  id: '/finanzen/',
  path: '/finanzen/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzenNeueRechnungRoute =
  AdminFinanzenNeueRechnungRouteImport.update({
    id: '/finanzen/neue-rechnung',
    path: '/finanzen/neue-rechnung',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKundenIndexRoute = AdminKundenIndexRouteImport.update({
  id: '/kunden/',
  path: '/kunden/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKundenIdRoute = AdminKundenIdRouteImport.update({
  id: '/kunden/$id',
  path: '/kunden/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteBestellungenRoute =
  AdminWebsiteBestellungenRouteImport.update({
    id: '/website/bestellungen',
    path: '/website/bestellungen',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWebsiteEinstellungenRoute =
  AdminWebsiteEinstellungenRouteImport.update({
    id: '/website/einstellungen',
    path: '/website/einstellungen',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWebsiteKundenRoute = AdminWebsiteKundenRouteImport.update({
  id: '/website/kunden',
  path: '/website/kunden',
  getParentRoute: () => AdminRoute,
} as any)
const WebsiteAdminBestellungenIndexRoute =
  WebsiteAdminBestellungenIndexRouteImport.update({
    id: '/bestellungen/',
    path: '/bestellungen/',
    getParentRoute: () => WebsiteAdminRoute,
  } as any)
const WebsiteAdminBestellungenIdRoute =
  WebsiteAdminBestellungenIdRouteImport.update({
    id: '/bestellungen/$id',
    path: '/bestellungen/$id',
    getParentRoute: () => WebsiteAdminRoute,
  } as any)
const AdminAuftraegeIdIndexRoute = AdminAuftraegeIdIndexRouteImport.update({
  id: '/auftraege/$id/',
  path: '/auftraege/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuftraegeIdPlattenRoute = AdminAuftraegeIdPlattenRouteImport.update({
  id: '/auftraege/$id/platten',
  path: '/auftraege/$id/platten',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzenAbrechnungenIndexRoute =
  AdminFinanzenAbrechnungenIndexRouteImport.update({
    id: '/finanzen/abrechnungen/',
    path: '/finanzen/abrechnungen/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinanzenAbrechnungenIdRoute =
  AdminFinanzenAbrechnungenIdRouteImport.update({
    id: '/finanzen/abrechnungen/$id',
    path: '/finanzen/abrechnungen/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShopBestellungenIdRoute = AdminShopBestellungenIdRouteImport.update({
  id: '/shop/bestellungen/$id',
  path: '/shop/bestellungen/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anfragen': typeof AnfragenRoute
  '/anmelden': typeof AnmeldenRoute
  '/chat': typeof ChatRoute
  '/einstellungen': typeof EinstellungenRoute
  '/ersatzteile': typeof ErsatzteileRoute
  '/filamente': typeof FilamenteRoute
  '/kalender': typeof KalenderRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kleinserien': typeof KleinserienRoute
  '/login': typeof LoginRoute
  '/mein-konto': typeof MeinKontoRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/portal': typeof PortalRouteWithChildren
  '/profil-ergaenzen': typeof ProfilErgaenzenRoute
  '/profil-vervollstaendigen': typeof ProfilVervollstaendigenRoute
  '/prototypen': typeof PrototypenRoute
  '/registrieren': typeof RegistrierenRoute
  '/teile': typeof TeileRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/uploads': typeof UploadsRoute
  '/website-admin': typeof WebsiteAdminRouteWithChildren
  '/3d-druck-bern': typeof Site3dDruckBernRoute
  '/3d-druck-ostschweiz': typeof Site3dDruckOstschweizRoute
  '/3d-druck-st-gallen': typeof Site3dDruckStGallenRoute
  '/3d-druck-winterthur': typeof Site3dDruckWinterthurRoute
  '/3d-druck-zuerich': typeof Site3dDruckZuerichRoute
  '/agb': typeof SiteAgbRoute
  '/datenschutz': typeof SiteDatenschutzRoute
  '/faq': typeof SiteFaqRoute
  '/impressum': typeof SiteImpressumRoute
  '/kalkulator-online': typeof SiteKalkulatorOnlineRoute
  '/kontakt': typeof SiteKontaktRoute
  '/maschinen': typeof SiteMaschinenRoute
  '/ueber-ki': typeof SiteUeberKiRoute
  '/ueber-uns': typeof SiteUeberUnsRoute
  '/admin/anfragen': typeof AdminAnfragenRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/druckplatten': typeof AdminDruckplattenRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/filamente': typeof AdminFilamenteRoute
  '/admin/kalender': typeof AdminKalenderRoute
  '/admin/kalkulator': typeof AdminKalkulatorRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/teile': typeof AdminTeileRoute
  '/admin/login': typeof AdminLoginRoute
  '/auftraege/$id': typeof AuftraegeIdRoute
  '/bewertung/$token': typeof BewertungTokenRoute
  '/kunden/$id': typeof KundenIdRoute
  '/portal/bestellungen': typeof PortalBestellungenRoute
  '/portal/dokumente': typeof PortalDokumenteRoute
  '/portal/passwort': typeof PortalPasswortRoute
  '/portal/profil': typeof PortalProfilRoute
  '/upload/$token': typeof UploadTokenRoute
  '/website-admin/analyse': typeof WebsiteAdminAnalyseRoute
  '/website-admin/blog': typeof WebsiteAdminBlogRoute
  '/website-admin/chat': typeof WebsiteAdminChatRoute
  '/website-admin/einstellungen': typeof WebsiteAdminEinstellungenRoute
  '/website-admin/equipment': typeof WebsiteAdminEquipmentRoute
  '/website-admin/kunden': typeof WebsiteAdminKundenRoute
  '/website-admin/navigation': typeof WebsiteAdminNavigationRoute
  '/website-admin/partner': typeof WebsiteAdminPartnerRoute
  '/website-admin/projekte': typeof WebsiteAdminProjekteRoute
  '/website-admin/reviews': typeof WebsiteAdminReviewsRoute
  '/website-admin/shop': typeof WebsiteAdminShopRoute
  '/website-admin/shop-produkte': typeof WebsiteAdminShopProdukteRoute
  '/website-admin/team': typeof WebsiteAdminTeamRoute
  '/website-admin/timeline': typeof WebsiteAdminTimelineRoute
  '/website/$': typeof WebsiteSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/auftraege/': typeof AuftraegeIndexRoute
  '/bewertung/': typeof BewertungIndexRoute
  '/kunden/': typeof KundenIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/website-admin/': typeof WebsiteAdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/leistungen/$slug': typeof SiteLeistungenSlugRoute
  '/materialien/$slug': typeof SiteMaterialienSlugRoute
  '/newsletter/abmelden': typeof SiteNewsletterAbmeldenRoute
  '/projekte/$slug': typeof SiteProjekteSlugRoute
  '/shop/$slug': typeof SiteShopSlugRoute
  '/standorte/$slug': typeof SiteStandorteSlugRoute
  '/vergleich/$slug': typeof SiteVergleichSlugRoute
  '/wissen/3d-druck-kosten-schweiz': typeof SiteWissen3dDruckKostenSchweizRoute
  '/admin/finanzen/neue-rechnung': typeof AdminFinanzenNeueRechnungRoute
  '/admin/kunden/$id': typeof AdminKundenIdRoute
  '/admin/website/bestellungen': typeof AdminWebsiteBestellungenRoute
  '/admin/website/einstellungen': typeof AdminWebsiteEinstellungenRoute
  '/admin/website/kunden': typeof AdminWebsiteKundenRoute
  '/website-admin/bestellungen/$id': typeof WebsiteAdminBestellungenIdRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/leistungen/': typeof SiteLeistungenIndexRoute
  '/materialien/': typeof SiteMaterialienIndexRoute
  '/shop/': typeof SiteShopIndexRoute
  '/vergleich/': typeof SiteVergleichIndexRoute
  '/admin/auftraege/': typeof AdminAuftraegeIndexRoute
  '/admin/finanzen/': typeof AdminFinanzenIndexRoute
  '/admin/kunden/': typeof AdminKundenIndexRoute
  '/website-admin/bestellungen/': typeof WebsiteAdminBestellungenIndexRoute
  '/admin/auftraege/$id/platten': typeof AdminAuftraegeIdPlattenRoute
  '/admin/finanzen/abrechnungen/$id': typeof AdminFinanzenAbrechnungenIdRoute
  '/admin/shop/bestellungen/$id': typeof AdminShopBestellungenIdRoute
  '/admin/auftraege/$id/': typeof AdminAuftraegeIdIndexRoute
  '/admin/finanzen/abrechnungen/': typeof AdminFinanzenAbrechnungenIndexRoute
}
export interface FileRoutesByTo {
  '/anfragen': typeof AnfragenRoute
  '/anmelden': typeof AnmeldenRoute
  '/chat': typeof ChatRoute
  '/einstellungen': typeof EinstellungenRoute
  '/ersatzteile': typeof ErsatzteileRoute
  '/filamente': typeof FilamenteRoute
  '/kalender': typeof KalenderRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kleinserien': typeof KleinserienRoute
  '/login': typeof LoginRoute
  '/mein-konto': typeof MeinKontoRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profil-ergaenzen': typeof ProfilErgaenzenRoute
  '/profil-vervollstaendigen': typeof ProfilVervollstaendigenRoute
  '/prototypen': typeof PrototypenRoute
  '/registrieren': typeof RegistrierenRoute
  '/teile': typeof TeileRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/uploads': typeof UploadsRoute
  '/3d-druck-bern': typeof Site3dDruckBernRoute
  '/3d-druck-ostschweiz': typeof Site3dDruckOstschweizRoute
  '/3d-druck-st-gallen': typeof Site3dDruckStGallenRoute
  '/3d-druck-winterthur': typeof Site3dDruckWinterthurRoute
  '/3d-druck-zuerich': typeof Site3dDruckZuerichRoute
  '/agb': typeof SiteAgbRoute
  '/datenschutz': typeof SiteDatenschutzRoute
  '/faq': typeof SiteFaqRoute
  '/impressum': typeof SiteImpressumRoute
  '/kalkulator-online': typeof SiteKalkulatorOnlineRoute
  '/kontakt': typeof SiteKontaktRoute
  '/maschinen': typeof SiteMaschinenRoute
  '/ueber-ki': typeof SiteUeberKiRoute
  '/ueber-uns': typeof SiteUeberUnsRoute
  '/admin/anfragen': typeof AdminAnfragenRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/druckplatten': typeof AdminDruckplattenRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/filamente': typeof AdminFilamenteRoute
  '/admin/kalender': typeof AdminKalenderRoute
  '/admin/kalkulator': typeof AdminKalkulatorRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/teile': typeof AdminTeileRoute
  '/admin/login': typeof AdminLoginRoute
  '/auftraege/$id': typeof AuftraegeIdRoute
  '/bewertung/$token': typeof BewertungTokenRoute
  '/kunden/$id': typeof KundenIdRoute
  '/portal/bestellungen': typeof PortalBestellungenRoute
  '/portal/dokumente': typeof PortalDokumenteRoute
  '/portal/passwort': typeof PortalPasswortRoute
  '/portal/profil': typeof PortalProfilRoute
  '/upload/$token': typeof UploadTokenRoute
  '/website-admin/analyse': typeof WebsiteAdminAnalyseRoute
  '/website-admin/blog': typeof WebsiteAdminBlogRoute
  '/website-admin/chat': typeof WebsiteAdminChatRoute
  '/website-admin/einstellungen': typeof WebsiteAdminEinstellungenRoute
  '/website-admin/equipment': typeof WebsiteAdminEquipmentRoute
  '/website-admin/kunden': typeof WebsiteAdminKundenRoute
  '/website-admin/navigation': typeof WebsiteAdminNavigationRoute
  '/website-admin/partner': typeof WebsiteAdminPartnerRoute
  '/website-admin/projekte': typeof WebsiteAdminProjekteRoute
  '/website-admin/reviews': typeof WebsiteAdminReviewsRoute
  '/website-admin/shop': typeof WebsiteAdminShopRoute
  '/website-admin/shop-produkte': typeof WebsiteAdminShopProdukteRoute
  '/website-admin/team': typeof WebsiteAdminTeamRoute
  '/website-admin/timeline': typeof WebsiteAdminTimelineRoute
  '/website/$': typeof WebsiteSplatRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auftraege': typeof AuftraegeIndexRoute
  '/bewertung': typeof BewertungIndexRoute
  '/kunden': typeof KundenIndexRoute
  '/portal': typeof PortalIndexRoute
  '/website-admin': typeof WebsiteAdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/leistungen/$slug': typeof SiteLeistungenSlugRoute
  '/materialien/$slug': typeof SiteMaterialienSlugRoute
  '/newsletter/abmelden': typeof SiteNewsletterAbmeldenRoute
  '/projekte/$slug': typeof SiteProjekteSlugRoute
  '/shop/$slug': typeof SiteShopSlugRoute
  '/standorte/$slug': typeof SiteStandorteSlugRoute
  '/vergleich/$slug': typeof SiteVergleichSlugRoute
  '/wissen/3d-druck-kosten-schweiz': typeof SiteWissen3dDruckKostenSchweizRoute
  '/admin/finanzen/neue-rechnung': typeof AdminFinanzenNeueRechnungRoute
  '/admin/kunden/$id': typeof AdminKundenIdRoute
  '/admin/website/bestellungen': typeof AdminWebsiteBestellungenRoute
  '/admin/website/einstellungen': typeof AdminWebsiteEinstellungenRoute
  '/admin/website/kunden': typeof AdminWebsiteKundenRoute
  '/website-admin/bestellungen/$id': typeof WebsiteAdminBestellungenIdRoute
  '/blog': typeof SiteBlogIndexRoute
  '/leistungen': typeof SiteLeistungenIndexRoute
  '/materialien': typeof SiteMaterialienIndexRoute
  '/shop': typeof SiteShopIndexRoute
  '/vergleich': typeof SiteVergleichIndexRoute
  '/admin/auftraege': typeof AdminAuftraegeIndexRoute
  '/admin/finanzen': typeof AdminFinanzenIndexRoute
  '/admin/kunden': typeof AdminKundenIndexRoute
  '/website-admin/bestellungen': typeof WebsiteAdminBestellungenIndexRoute
  '/admin/auftraege/$id/platten': typeof AdminAuftraegeIdPlattenRoute
  '/admin/finanzen/abrechnungen/$id': typeof AdminFinanzenAbrechnungenIdRoute
  '/admin/shop/bestellungen/$id': typeof AdminShopBestellungenIdRoute
  '/admin/auftraege/$id': typeof AdminAuftraegeIdIndexRoute
  '/admin/finanzen/abrechnungen': typeof AdminFinanzenAbrechnungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/anfragen': typeof AnfragenRoute
  '/anmelden': typeof AnmeldenRoute
  '/chat': typeof ChatRoute
  '/einstellungen': typeof EinstellungenRoute
  '/ersatzteile': typeof ErsatzteileRoute
  '/filamente': typeof FilamenteRoute
  '/kalender': typeof KalenderRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kleinserien': typeof KleinserienRoute
  '/login': typeof LoginRoute
  '/mein-konto': typeof MeinKontoRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/portal': typeof PortalRouteWithChildren
  '/profil-ergaenzen': typeof ProfilErgaenzenRoute
  '/profil-vervollstaendigen': typeof ProfilVervollstaendigenRoute
  '/prototypen': typeof PrototypenRoute
  '/registrieren': typeof RegistrierenRoute
  '/teile': typeof TeileRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/uploads': typeof UploadsRoute
  '/website-admin': typeof WebsiteAdminRouteWithChildren
  '/_site/3d-druck-bern': typeof Site3dDruckBernRoute
  '/_site/3d-druck-ostschweiz': typeof Site3dDruckOstschweizRoute
  '/_site/3d-druck-st-gallen': typeof Site3dDruckStGallenRoute
  '/_site/3d-druck-winterthur': typeof Site3dDruckWinterthurRoute
  '/_site/3d-druck-zuerich': typeof Site3dDruckZuerichRoute
  '/_site/agb': typeof SiteAgbRoute
  '/_site/datenschutz': typeof SiteDatenschutzRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/impressum': typeof SiteImpressumRoute
  '/_site/kalkulator-online': typeof SiteKalkulatorOnlineRoute
  '/_site/kontakt': typeof SiteKontaktRoute
  '/_site/maschinen': typeof SiteMaschinenRoute
  '/_site/ueber-ki': typeof SiteUeberKiRoute
  '/_site/ueber-uns': typeof SiteUeberUnsRoute
  '/admin/anfragen': typeof AdminAnfragenRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/druckplatten': typeof AdminDruckplattenRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/filamente': typeof AdminFilamenteRoute
  '/admin/kalender': typeof AdminKalenderRoute
  '/admin/kalkulator': typeof AdminKalkulatorRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/teile': typeof AdminTeileRoute
  '/admin_/login': typeof AdminLoginRoute
  '/auftraege/$id': typeof AuftraegeIdRoute
  '/bewertung/$token': typeof BewertungTokenRoute
  '/kunden/$id': typeof KundenIdRoute
  '/portal/bestellungen': typeof PortalBestellungenRoute
  '/portal/dokumente': typeof PortalDokumenteRoute
  '/portal/passwort': typeof PortalPasswortRoute
  '/portal/profil': typeof PortalProfilRoute
  '/upload/$token': typeof UploadTokenRoute
  '/website-admin/analyse': typeof WebsiteAdminAnalyseRoute
  '/website-admin/blog': typeof WebsiteAdminBlogRoute
  '/website-admin/chat': typeof WebsiteAdminChatRoute
  '/website-admin/einstellungen': typeof WebsiteAdminEinstellungenRoute
  '/website-admin/equipment': typeof WebsiteAdminEquipmentRoute
  '/website-admin/kunden': typeof WebsiteAdminKundenRoute
  '/website-admin/navigation': typeof WebsiteAdminNavigationRoute
  '/website-admin/partner': typeof WebsiteAdminPartnerRoute
  '/website-admin/projekte': typeof WebsiteAdminProjekteRoute
  '/website-admin/reviews': typeof WebsiteAdminReviewsRoute
  '/website-admin/shop': typeof WebsiteAdminShopRoute
  '/website-admin/shop-produkte': typeof WebsiteAdminShopProdukteRoute
  '/website-admin/team': typeof WebsiteAdminTeamRoute
  '/website-admin/timeline': typeof WebsiteAdminTimelineRoute
  '/website/$': typeof WebsiteSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auftraege/': typeof AuftraegeIndexRoute
  '/bewertung/': typeof BewertungIndexRoute
  '/kunden/': typeof KundenIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/website-admin/': typeof WebsiteAdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/leistungen/$slug': typeof SiteLeistungenSlugRoute
  '/_site/materialien/$slug': typeof SiteMaterialienSlugRoute
  '/_site/newsletter/abmelden': typeof SiteNewsletterAbmeldenRoute
  '/_site/projekte/$slug': typeof SiteProjekteSlugRoute
  '/_site/shop/$slug': typeof SiteShopSlugRoute
  '/_site/standorte/$slug': typeof SiteStandorteSlugRoute
  '/_site/vergleich/$slug': typeof SiteVergleichSlugRoute
  '/_site/wissen/3d-druck-kosten-schweiz': typeof SiteWissen3dDruckKostenSchweizRoute
  '/admin/finanzen/neue-rechnung': typeof AdminFinanzenNeueRechnungRoute
  '/admin/kunden/$id': typeof AdminKundenIdRoute
  '/admin/website/bestellungen': typeof AdminWebsiteBestellungenRoute
  '/admin/website/einstellungen': typeof AdminWebsiteEinstellungenRoute
  '/admin/website/kunden': typeof AdminWebsiteKundenRoute
  '/website-admin/bestellungen/$id': typeof WebsiteAdminBestellungenIdRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/leistungen/': typeof SiteLeistungenIndexRoute
  '/_site/materialien/': typeof SiteMaterialienIndexRoute
  '/_site/shop/': typeof SiteShopIndexRoute
  '/_site/vergleich/': typeof SiteVergleichIndexRoute
  '/admin/auftraege/': typeof AdminAuftraegeIndexRoute
  '/admin/finanzen/': typeof AdminFinanzenIndexRoute
  '/admin/kunden/': typeof AdminKundenIndexRoute
  '/website-admin/bestellungen/': typeof WebsiteAdminBestellungenIndexRoute
  '/admin/auftraege/$id/platten': typeof AdminAuftraegeIdPlattenRoute
  '/admin/finanzen/abrechnungen/$id': typeof AdminFinanzenAbrechnungenIdRoute
  '/admin/shop/bestellungen/$id': typeof AdminShopBestellungenIdRoute
  '/admin/auftraege/$id/': typeof AdminAuftraegeIdIndexRoute
  '/admin/finanzen/abrechnungen/': typeof AdminFinanzenAbrechnungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anfragen'
    | '/anmelden'
    | '/chat'
    | '/einstellungen'
    | '/ersatzteile'
    | '/filamente'
    | '/kalender'
    | '/kalkulator'
    | '/kleinserien'
    | '/login'
    | '/mein-konto'
    | '/payment-success'
    | '/portal'
    | '/profil-ergaenzen'
    | '/profil-vervollstaendigen'
    | '/prototypen'
    | '/registrieren'
    | '/teile'
    | '/unsubscribe'
    | '/uploads'
    | '/website-admin'
    | '/3d-druck-bern'
    | '/3d-druck-ostschweiz'
    | '/3d-druck-st-gallen'
    | '/3d-druck-winterthur'
    | '/3d-druck-zuerich'
    | '/agb'
    | '/datenschutz'
    | '/faq'
    | '/impressum'
    | '/kalkulator-online'
    | '/kontakt'
    | '/maschinen'
    | '/ueber-ki'
    | '/ueber-uns'
    | '/admin/anfragen'
    | '/admin/chat'
    | '/admin/druckplatten'
    | '/admin/einstellungen'
    | '/admin/filamente'
    | '/admin/kalender'
    | '/admin/kalkulator'
    | '/admin/newsletter'
    | '/admin/teile'
    | '/admin/login'
    | '/auftraege/$id'
    | '/bewertung/$token'
    | '/kunden/$id'
    | '/portal/bestellungen'
    | '/portal/dokumente'
    | '/portal/passwort'
    | '/portal/profil'
    | '/upload/$token'
    | '/website-admin/analyse'
    | '/website-admin/blog'
    | '/website-admin/chat'
    | '/website-admin/einstellungen'
    | '/website-admin/equipment'
    | '/website-admin/kunden'
    | '/website-admin/navigation'
    | '/website-admin/partner'
    | '/website-admin/projekte'
    | '/website-admin/reviews'
    | '/website-admin/shop'
    | '/website-admin/shop-produkte'
    | '/website-admin/team'
    | '/website-admin/timeline'
    | '/website/$'
    | '/admin/'
    | '/auftraege/'
    | '/bewertung/'
    | '/kunden/'
    | '/portal/'
    | '/website-admin/'
    | '/.lovable/oauth/consent'
    | '/blog/$slug'
    | '/leistungen/$slug'
    | '/materialien/$slug'
    | '/newsletter/abmelden'
    | '/projekte/$slug'
    | '/shop/$slug'
    | '/standorte/$slug'
    | '/vergleich/$slug'
    | '/wissen/3d-druck-kosten-schweiz'
    | '/admin/finanzen/neue-rechnung'
    | '/admin/kunden/$id'
    | '/admin/website/bestellungen'
    | '/admin/website/einstellungen'
    | '/admin/website/kunden'
    | '/website-admin/bestellungen/$id'
    | '/blog/'
    | '/leistungen/'
    | '/materialien/'
    | '/shop/'
    | '/vergleich/'
    | '/admin/auftraege/'
    | '/admin/finanzen/'
    | '/admin/kunden/'
    | '/website-admin/bestellungen/'
    | '/admin/auftraege/$id/platten'
    | '/admin/finanzen/abrechnungen/$id'
    | '/admin/shop/bestellungen/$id'
    | '/admin/auftraege/$id/'
    | '/admin/finanzen/abrechnungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anfragen'
    | '/anmelden'
    | '/chat'
    | '/einstellungen'
    | '/ersatzteile'
    | '/filamente'
    | '/kalender'
    | '/kalkulator'
    | '/kleinserien'
    | '/login'
    | '/mein-konto'
    | '/payment-success'
    | '/profil-ergaenzen'
    | '/profil-vervollstaendigen'
    | '/prototypen'
    | '/registrieren'
    | '/teile'
    | '/unsubscribe'
    | '/uploads'
    | '/3d-druck-bern'
    | '/3d-druck-ostschweiz'
    | '/3d-druck-st-gallen'
    | '/3d-druck-winterthur'
    | '/3d-druck-zuerich'
    | '/agb'
    | '/datenschutz'
    | '/faq'
    | '/impressum'
    | '/kalkulator-online'
    | '/kontakt'
    | '/maschinen'
    | '/ueber-ki'
    | '/ueber-uns'
    | '/admin/anfragen'
    | '/admin/chat'
    | '/admin/druckplatten'
    | '/admin/einstellungen'
    | '/admin/filamente'
    | '/admin/kalender'
    | '/admin/kalkulator'
    | '/admin/newsletter'
    | '/admin/teile'
    | '/admin/login'
    | '/auftraege/$id'
    | '/bewertung/$token'
    | '/kunden/$id'
    | '/portal/bestellungen'
    | '/portal/dokumente'
    | '/portal/passwort'
    | '/portal/profil'
    | '/upload/$token'
    | '/website-admin/analyse'
    | '/website-admin/blog'
    | '/website-admin/chat'
    | '/website-admin/einstellungen'
    | '/website-admin/equipment'
    | '/website-admin/kunden'
    | '/website-admin/navigation'
    | '/website-admin/partner'
    | '/website-admin/projekte'
    | '/website-admin/reviews'
    | '/website-admin/shop'
    | '/website-admin/shop-produkte'
    | '/website-admin/team'
    | '/website-admin/timeline'
    | '/website/$'
    | '/'
    | '/admin'
    | '/auftraege'
    | '/bewertung'
    | '/kunden'
    | '/portal'
    | '/website-admin'
    | '/.lovable/oauth/consent'
    | '/blog/$slug'
    | '/leistungen/$slug'
    | '/materialien/$slug'
    | '/newsletter/abmelden'
    | '/projekte/$slug'
    | '/shop/$slug'
    | '/standorte/$slug'
    | '/vergleich/$slug'
    | '/wissen/3d-druck-kosten-schweiz'
    | '/admin/finanzen/neue-rechnung'
    | '/admin/kunden/$id'
    | '/admin/website/bestellungen'
    | '/admin/website/einstellungen'
    | '/admin/website/kunden'
    | '/website-admin/bestellungen/$id'
    | '/blog'
    | '/leistungen'
    | '/materialien'
    | '/shop'
    | '/vergleich'
    | '/admin/auftraege'
    | '/admin/finanzen'
    | '/admin/kunden'
    | '/website-admin/bestellungen'
    | '/admin/auftraege/$id/platten'
    | '/admin/finanzen/abrechnungen/$id'
    | '/admin/shop/bestellungen/$id'
    | '/admin/auftraege/$id'
    | '/admin/finanzen/abrechnungen'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/anfragen'
    | '/anmelden'
    | '/chat'
    | '/einstellungen'
    | '/ersatzteile'
    | '/filamente'
    | '/kalender'
    | '/kalkulator'
    | '/kleinserien'
    | '/login'
    | '/mein-konto'
    | '/payment-success'
    | '/portal'
    | '/profil-ergaenzen'
    | '/profil-vervollstaendigen'
    | '/prototypen'
    | '/registrieren'
    | '/teile'
    | '/unsubscribe'
    | '/uploads'
    | '/website-admin'
    | '/_site/3d-druck-bern'
    | '/_site/3d-druck-ostschweiz'
    | '/_site/3d-druck-st-gallen'
    | '/_site/3d-druck-winterthur'
    | '/_site/3d-druck-zuerich'
    | '/_site/agb'
    | '/_site/datenschutz'
    | '/_site/faq'
    | '/_site/impressum'
    | '/_site/kalkulator-online'
    | '/_site/kontakt'
    | '/_site/maschinen'
    | '/_site/ueber-ki'
    | '/_site/ueber-uns'
    | '/admin/anfragen'
    | '/admin/chat'
    | '/admin/druckplatten'
    | '/admin/einstellungen'
    | '/admin/filamente'
    | '/admin/kalender'
    | '/admin/kalkulator'
    | '/admin/newsletter'
    | '/admin/teile'
    | '/admin_/login'
    | '/auftraege/$id'
    | '/bewertung/$token'
    | '/kunden/$id'
    | '/portal/bestellungen'
    | '/portal/dokumente'
    | '/portal/passwort'
    | '/portal/profil'
    | '/upload/$token'
    | '/website-admin/analyse'
    | '/website-admin/blog'
    | '/website-admin/chat'
    | '/website-admin/einstellungen'
    | '/website-admin/equipment'
    | '/website-admin/kunden'
    | '/website-admin/navigation'
    | '/website-admin/partner'
    | '/website-admin/projekte'
    | '/website-admin/reviews'
    | '/website-admin/shop'
    | '/website-admin/shop-produkte'
    | '/website-admin/team'
    | '/website-admin/timeline'
    | '/website/$'
    | '/_site/'
    | '/admin/'
    | '/auftraege/'
    | '/bewertung/'
    | '/kunden/'
    | '/portal/'
    | '/website-admin/'
    | '/.lovable/oauth/consent'
    | '/_site/blog/$slug'
    | '/_site/leistungen/$slug'
    | '/_site/materialien/$slug'
    | '/_site/newsletter/abmelden'
    | '/_site/projekte/$slug'
    | '/_site/shop/$slug'
    | '/_site/standorte/$slug'
    | '/_site/vergleich/$slug'
    | '/_site/wissen/3d-druck-kosten-schweiz'
    | '/admin/finanzen/neue-rechnung'
    | '/admin/kunden/$id'
    | '/admin/website/bestellungen'
    | '/admin/website/einstellungen'
    | '/admin/website/kunden'
    | '/website-admin/bestellungen/$id'
    | '/_site/blog/'
    | '/_site/leistungen/'
    | '/_site/materialien/'
    | '/_site/shop/'
    | '/_site/vergleich/'
    | '/admin/auftraege/'
    | '/admin/finanzen/'
    | '/admin/kunden/'
    | '/website-admin/bestellungen/'
    | '/admin/auftraege/$id/platten'
    | '/admin/finanzen/abrechnungen/$id'
    | '/admin/shop/bestellungen/$id'
    | '/admin/auftraege/$id/'
    | '/admin/finanzen/abrechnungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AnfragenRoute: typeof AnfragenRoute
  AnmeldenRoute: typeof AnmeldenRoute
  ChatRoute: typeof ChatRoute
  EinstellungenRoute: typeof EinstellungenRoute
  ErsatzteileRoute: typeof ErsatzteileRoute
  FilamenteRoute: typeof FilamenteRoute
  KalenderRoute: typeof KalenderRoute
  KalkulatorRoute: typeof KalkulatorRoute
  KleinserienRoute: typeof KleinserienRoute
  LoginRoute: typeof LoginRoute
  MeinKontoRoute: typeof MeinKontoRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProfilErgaenzenRoute: typeof ProfilErgaenzenRoute
  ProfilVervollstaendigenRoute: typeof ProfilVervollstaendigenRoute
  PrototypenRoute: typeof PrototypenRoute
  RegistrierenRoute: typeof RegistrierenRoute
  TeileRoute: typeof TeileRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  UploadsRoute: typeof UploadsRoute
  WebsiteAdminRoute: typeof WebsiteAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuftraegeIdRoute: typeof AuftraegeIdRoute
  BewertungTokenRoute: typeof BewertungTokenRoute
  KundenIdRoute: typeof KundenIdRoute
  UploadTokenRoute: typeof UploadTokenRoute
  WebsiteSplatRoute: typeof WebsiteSplatRoute
  AuftraegeIndexRoute: typeof AuftraegeIndexRoute
  BewertungIndexRoute: typeof BewertungIndexRoute
  KundenIndexRoute: typeof KundenIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfragen': {
      id: '/anfragen'
      path: '/anfragen'
      fullPath: '/anfragen'
      preLoaderRoute: typeof AnfragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ersatzteile': {
      id: '/ersatzteile'
      path: '/ersatzteile'
      fullPath: '/ersatzteile'
      preLoaderRoute: typeof ErsatzteileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filamente': {
      id: '/filamente'
      path: '/filamente'
      fullPath: '/filamente'
      preLoaderRoute: typeof FilamenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator': {
      id: '/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof KalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kleinserien': {
      id: '/kleinserien'
      path: '/kleinserien'
      fullPath: '/kleinserien'
      preLoaderRoute: typeof KleinserienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mein-konto': {
      id: '/mein-konto'
      path: '/mein-konto'
      fullPath: '/mein-konto'
      preLoaderRoute: typeof MeinKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-ergaenzen': {
      id: '/profil-ergaenzen'
      path: '/profil-ergaenzen'
      fullPath: '/profil-ergaenzen'
      preLoaderRoute: typeof ProfilErgaenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-vervollstaendigen': {
      id: '/profil-vervollstaendigen'
      path: '/profil-vervollstaendigen'
      fullPath: '/profil-vervollstaendigen'
      preLoaderRoute: typeof ProfilVervollstaendigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypen': {
      id: '/prototypen'
      path: '/prototypen'
      fullPath: '/prototypen'
      preLoaderRoute: typeof PrototypenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teile': {
      id: '/teile'
      path: '/teile'
      fullPath: '/teile'
      preLoaderRoute: typeof TeileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-admin': {
      id: '/website-admin'
      path: '/website-admin'
      fullPath: '/website-admin'
      preLoaderRoute: typeof WebsiteAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/3d-druck-bern': {
      id: '/_site/3d-druck-bern'
      path: '/3d-druck-bern'
      fullPath: '/3d-druck-bern'
      preLoaderRoute: typeof Site3dDruckBernRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/3d-druck-ostschweiz': {
      id: '/_site/3d-druck-ostschweiz'
      path: '/3d-druck-ostschweiz'
      fullPath: '/3d-druck-ostschweiz'
      preLoaderRoute: typeof Site3dDruckOstschweizRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/3d-druck-st-gallen': {
      id: '/_site/3d-druck-st-gallen'
      path: '/3d-druck-st-gallen'
      fullPath: '/3d-druck-st-gallen'
      preLoaderRoute: typeof Site3dDruckStGallenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/3d-druck-winterthur': {
      id: '/_site/3d-druck-winterthur'
      path: '/3d-druck-winterthur'
      fullPath: '/3d-druck-winterthur'
      preLoaderRoute: typeof Site3dDruckWinterthurRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/3d-druck-zuerich': {
      id: '/_site/3d-druck-zuerich'
      path: '/3d-druck-zuerich'
      fullPath: '/3d-druck-zuerich'
      preLoaderRoute: typeof Site3dDruckZuerichRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/agb': {
      id: '/_site/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof SiteAgbRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/datenschutz': {
      id: '/_site/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof SiteDatenschutzRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/impressum': {
      id: '/_site/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof SiteImpressumRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kalkulator-online': {
      id: '/_site/kalkulator-online'
      path: '/kalkulator-online'
      fullPath: '/kalkulator-online'
      preLoaderRoute: typeof SiteKalkulatorOnlineRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kontakt': {
      id: '/_site/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof SiteKontaktRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/maschinen': {
      id: '/_site/maschinen'
      path: '/maschinen'
      fullPath: '/maschinen'
      preLoaderRoute: typeof SiteMaschinenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ueber-ki': {
      id: '/_site/ueber-ki'
      path: '/ueber-ki'
      fullPath: '/ueber-ki'
      preLoaderRoute: typeof SiteUeberKiRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ueber-uns': {
      id: '/_site/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof SiteUeberUnsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anfragen': {
      id: '/admin/anfragen'
      path: '/anfragen'
      fullPath: '/admin/anfragen'
      preLoaderRoute: typeof AdminAnfragenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/druckplatten': {
      id: '/admin/druckplatten'
      path: '/druckplatten'
      fullPath: '/admin/druckplatten'
      preLoaderRoute: typeof AdminDruckplattenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/einstellungen': {
      id: '/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AdminEinstellungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/filamente': {
      id: '/admin/filamente'
      path: '/filamente'
      fullPath: '/admin/filamente'
      preLoaderRoute: typeof AdminFilamenteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kalender': {
      id: '/admin/kalender'
      path: '/kalender'
      fullPath: '/admin/kalender'
      preLoaderRoute: typeof AdminKalenderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kalkulator': {
      id: '/admin/kalkulator'
      path: '/kalkulator'
      fullPath: '/admin/kalkulator'
      preLoaderRoute: typeof AdminKalkulatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teile': {
      id: '/admin/teile'
      path: '/teile'
      fullPath: '/admin/teile'
      preLoaderRoute: typeof AdminTeileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auftraege/': {
      id: '/auftraege/'
      path: '/auftraege'
      fullPath: '/auftraege/'
      preLoaderRoute: typeof AuftraegeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auftraege/$id': {
      id: '/auftraege/$id'
      path: '/auftraege/$id'
      fullPath: '/auftraege/$id'
      preLoaderRoute: typeof AuftraegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewertung/': {
      id: '/bewertung/'
      path: '/bewertung'
      fullPath: '/bewertung/'
      preLoaderRoute: typeof BewertungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewertung/$token': {
      id: '/bewertung/$token'
      path: '/bewertung/$token'
      fullPath: '/bewertung/$token'
      preLoaderRoute: typeof BewertungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden/': {
      id: '/kunden/'
      path: '/kunden'
      fullPath: '/kunden/'
      preLoaderRoute: typeof KundenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden/$id': {
      id: '/kunden/$id'
      path: '/kunden/$id'
      fullPath: '/kunden/$id'
      preLoaderRoute: typeof KundenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bestellungen': {
      id: '/portal/bestellungen'
      path: '/bestellungen'
      fullPath: '/portal/bestellungen'
      preLoaderRoute: typeof PortalBestellungenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dokumente': {
      id: '/portal/dokumente'
      path: '/dokumente'
      fullPath: '/portal/dokumente'
      preLoaderRoute: typeof PortalDokumenteRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/passwort': {
      id: '/portal/passwort'
      path: '/passwort'
      fullPath: '/portal/passwort'
      preLoaderRoute: typeof PortalPasswortRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profil': {
      id: '/portal/profil'
      path: '/profil'
      fullPath: '/portal/profil'
      preLoaderRoute: typeof PortalProfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-admin/': {
      id: '/website-admin/'
      path: '/'
      fullPath: '/website-admin/'
      preLoaderRoute: typeof WebsiteAdminIndexRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/analyse': {
      id: '/website-admin/analyse'
      path: '/analyse'
      fullPath: '/website-admin/analyse'
      preLoaderRoute: typeof WebsiteAdminAnalyseRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/blog': {
      id: '/website-admin/blog'
      path: '/blog'
      fullPath: '/website-admin/blog'
      preLoaderRoute: typeof WebsiteAdminBlogRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/chat': {
      id: '/website-admin/chat'
      path: '/chat'
      fullPath: '/website-admin/chat'
      preLoaderRoute: typeof WebsiteAdminChatRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/einstellungen': {
      id: '/website-admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/website-admin/einstellungen'
      preLoaderRoute: typeof WebsiteAdminEinstellungenRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/equipment': {
      id: '/website-admin/equipment'
      path: '/equipment'
      fullPath: '/website-admin/equipment'
      preLoaderRoute: typeof WebsiteAdminEquipmentRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/kunden': {
      id: '/website-admin/kunden'
      path: '/kunden'
      fullPath: '/website-admin/kunden'
      preLoaderRoute: typeof WebsiteAdminKundenRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/navigation': {
      id: '/website-admin/navigation'
      path: '/navigation'
      fullPath: '/website-admin/navigation'
      preLoaderRoute: typeof WebsiteAdminNavigationRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/partner': {
      id: '/website-admin/partner'
      path: '/partner'
      fullPath: '/website-admin/partner'
      preLoaderRoute: typeof WebsiteAdminPartnerRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/projekte': {
      id: '/website-admin/projekte'
      path: '/projekte'
      fullPath: '/website-admin/projekte'
      preLoaderRoute: typeof WebsiteAdminProjekteRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/reviews': {
      id: '/website-admin/reviews'
      path: '/reviews'
      fullPath: '/website-admin/reviews'
      preLoaderRoute: typeof WebsiteAdminReviewsRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/shop': {
      id: '/website-admin/shop'
      path: '/shop'
      fullPath: '/website-admin/shop'
      preLoaderRoute: typeof WebsiteAdminShopRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/shop-produkte': {
      id: '/website-admin/shop-produkte'
      path: '/shop-produkte'
      fullPath: '/website-admin/shop-produkte'
      preLoaderRoute: typeof WebsiteAdminShopProdukteRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/team': {
      id: '/website-admin/team'
      path: '/team'
      fullPath: '/website-admin/team'
      preLoaderRoute: typeof WebsiteAdminTeamRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/timeline': {
      id: '/website-admin/timeline'
      path: '/timeline'
      fullPath: '/website-admin/timeline'
      preLoaderRoute: typeof WebsiteAdminTimelineRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website/$': {
      id: '/website/$'
      path: '/website/$'
      fullPath: '/website/$'
      preLoaderRoute: typeof WebsiteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/leistungen/': {
      id: '/_site/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof SiteLeistungenIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/leistungen/$slug': {
      id: '/_site/leistungen/$slug'
      path: '/leistungen/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof SiteLeistungenSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/materialien/': {
      id: '/_site/materialien/'
      path: '/materialien'
      fullPath: '/materialien/'
      preLoaderRoute: typeof SiteMaterialienIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/materialien/$slug': {
      id: '/_site/materialien/$slug'
      path: '/materialien/$slug'
      fullPath: '/materialien/$slug'
      preLoaderRoute: typeof SiteMaterialienSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/newsletter/abmelden': {
      id: '/_site/newsletter/abmelden'
      path: '/newsletter/abmelden'
      fullPath: '/newsletter/abmelden'
      preLoaderRoute: typeof SiteNewsletterAbmeldenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projekte/$slug': {
      id: '/_site/projekte/$slug'
      path: '/projekte/$slug'
      fullPath: '/projekte/$slug'
      preLoaderRoute: typeof SiteProjekteSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop/': {
      id: '/_site/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof SiteShopIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop/$slug': {
      id: '/_site/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof SiteShopSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/standorte/$slug': {
      id: '/_site/standorte/$slug'
      path: '/standorte/$slug'
      fullPath: '/standorte/$slug'
      preLoaderRoute: typeof SiteStandorteSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/vergleich/': {
      id: '/_site/vergleich/'
      path: '/vergleich'
      fullPath: '/vergleich/'
      preLoaderRoute: typeof SiteVergleichIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/vergleich/$slug': {
      id: '/_site/vergleich/$slug'
      path: '/vergleich/$slug'
      fullPath: '/vergleich/$slug'
      preLoaderRoute: typeof SiteVergleichSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/wissen/3d-druck-kosten-schweiz': {
      id: '/_site/wissen/3d-druck-kosten-schweiz'
      path: '/wissen/3d-druck-kosten-schweiz'
      fullPath: '/wissen/3d-druck-kosten-schweiz'
      preLoaderRoute: typeof SiteWissen3dDruckKostenSchweizRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/auftraege/': {
      id: '/admin/auftraege/'
      path: '/auftraege'
      fullPath: '/admin/auftraege/'
      preLoaderRoute: typeof AdminAuftraegeIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzen/': {
      id: '/admin/finanzen/'
      path: '/finanzen'
      fullPath: '/admin/finanzen/'
      preLoaderRoute: typeof AdminFinanzenIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzen/neue-rechnung': {
      id: '/admin/finanzen/neue-rechnung'
      path: '/finanzen/neue-rechnung'
      fullPath: '/admin/finanzen/neue-rechnung'
      preLoaderRoute: typeof AdminFinanzenNeueRechnungRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kunden/': {
      id: '/admin/kunden/'
      path: '/kunden'
      fullPath: '/admin/kunden/'
      preLoaderRoute: typeof AdminKundenIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kunden/$id': {
      id: '/admin/kunden/$id'
      path: '/kunden/$id'
      fullPath: '/admin/kunden/$id'
      preLoaderRoute: typeof AdminKundenIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/bestellungen': {
      id: '/admin/website/bestellungen'
      path: '/website/bestellungen'
      fullPath: '/admin/website/bestellungen'
      preLoaderRoute: typeof AdminWebsiteBestellungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/einstellungen': {
      id: '/admin/website/einstellungen'
      path: '/website/einstellungen'
      fullPath: '/admin/website/einstellungen'
      preLoaderRoute: typeof AdminWebsiteEinstellungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/kunden': {
      id: '/admin/website/kunden'
      path: '/website/kunden'
      fullPath: '/admin/website/kunden'
      preLoaderRoute: typeof AdminWebsiteKundenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/website-admin/bestellungen/': {
      id: '/website-admin/bestellungen/'
      path: '/bestellungen'
      fullPath: '/website-admin/bestellungen/'
      preLoaderRoute: typeof WebsiteAdminBestellungenIndexRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/website-admin/bestellungen/$id': {
      id: '/website-admin/bestellungen/$id'
      path: '/bestellungen/$id'
      fullPath: '/website-admin/bestellungen/$id'
      preLoaderRoute: typeof WebsiteAdminBestellungenIdRouteImport
      parentRoute: typeof WebsiteAdminRoute
    }
    '/admin/auftraege/$id/': {
      id: '/admin/auftraege/$id/'
      path: '/auftraege/$id'
      fullPath: '/admin/auftraege/$id/'
      preLoaderRoute: typeof AdminAuftraegeIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auftraege/$id/platten': {
      id: '/admin/auftraege/$id/platten'
      path: '/auftraege/$id/platten'
      fullPath: '/admin/auftraege/$id/platten'
      preLoaderRoute: typeof AdminAuftraegeIdPlattenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzen/abrechnungen/': {
      id: '/admin/finanzen/abrechnungen/'
      path: '/finanzen/abrechnungen'
      fullPath: '/admin/finanzen/abrechnungen/'
      preLoaderRoute: typeof AdminFinanzenAbrechnungenIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzen/abrechnungen/$id': {
      id: '/admin/finanzen/abrechnungen/$id'
      path: '/finanzen/abrechnungen/$id'
      fullPath: '/admin/finanzen/abrechnungen/$id'
      preLoaderRoute: typeof AdminFinanzenAbrechnungenIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop/bestellungen/$id': {
      id: '/admin/shop/bestellungen/$id'
      path: '/shop/bestellungen/$id'
      fullPath: '/admin/shop/bestellungen/$id'
      preLoaderRoute: typeof AdminShopBestellungenIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface SiteRouteChildren {
  Site3dDruckBernRoute: typeof Site3dDruckBernRoute
  Site3dDruckOstschweizRoute: typeof Site3dDruckOstschweizRoute
  Site3dDruckStGallenRoute: typeof Site3dDruckStGallenRoute
  Site3dDruckWinterthurRoute: typeof Site3dDruckWinterthurRoute
  Site3dDruckZuerichRoute: typeof Site3dDruckZuerichRoute
  SiteAgbRoute: typeof SiteAgbRoute
  SiteDatenschutzRoute: typeof SiteDatenschutzRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteImpressumRoute: typeof SiteImpressumRoute
  SiteKalkulatorOnlineRoute: typeof SiteKalkulatorOnlineRoute
  SiteKontaktRoute: typeof SiteKontaktRoute
  SiteMaschinenRoute: typeof SiteMaschinenRoute
  SiteUeberKiRoute: typeof SiteUeberKiRoute
  SiteUeberUnsRoute: typeof SiteUeberUnsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteLeistungenSlugRoute: typeof SiteLeistungenSlugRoute
  SiteMaterialienSlugRoute: typeof SiteMaterialienSlugRoute
  SiteNewsletterAbmeldenRoute: typeof SiteNewsletterAbmeldenRoute
  SiteProjekteSlugRoute: typeof SiteProjekteSlugRoute
  SiteShopSlugRoute: typeof SiteShopSlugRoute
  SiteStandorteSlugRoute: typeof SiteStandorteSlugRoute
  SiteVergleichSlugRoute: typeof SiteVergleichSlugRoute
  SiteWissen3dDruckKostenSchweizRoute: typeof SiteWissen3dDruckKostenSchweizRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteLeistungenIndexRoute: typeof SiteLeistungenIndexRoute
  SiteMaterialienIndexRoute: typeof SiteMaterialienIndexRoute
  SiteShopIndexRoute: typeof SiteShopIndexRoute
  SiteVergleichIndexRoute: typeof SiteVergleichIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  Site3dDruckBernRoute: Site3dDruckBernRoute,
  Site3dDruckOstschweizRoute: Site3dDruckOstschweizRoute,
  Site3dDruckStGallenRoute: Site3dDruckStGallenRoute,
  Site3dDruckWinterthurRoute: Site3dDruckWinterthurRoute,
  Site3dDruckZuerichRoute: Site3dDruckZuerichRoute,
  SiteAgbRoute: SiteAgbRoute,
  SiteDatenschutzRoute: SiteDatenschutzRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteImpressumRoute: SiteImpressumRoute,
  SiteKalkulatorOnlineRoute: SiteKalkulatorOnlineRoute,
  SiteKontaktRoute: SiteKontaktRoute,
  SiteMaschinenRoute: SiteMaschinenRoute,
  SiteUeberKiRoute: SiteUeberKiRoute,
  SiteUeberUnsRoute: SiteUeberUnsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteLeistungenSlugRoute: SiteLeistungenSlugRoute,
  SiteMaterialienSlugRoute: SiteMaterialienSlugRoute,
  SiteNewsletterAbmeldenRoute: SiteNewsletterAbmeldenRoute,
  SiteProjekteSlugRoute: SiteProjekteSlugRoute,
  SiteShopSlugRoute: SiteShopSlugRoute,
  SiteStandorteSlugRoute: SiteStandorteSlugRoute,
  SiteVergleichSlugRoute: SiteVergleichSlugRoute,
  SiteWissen3dDruckKostenSchweizRoute: SiteWissen3dDruckKostenSchweizRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteLeistungenIndexRoute: SiteLeistungenIndexRoute,
  SiteMaterialienIndexRoute: SiteMaterialienIndexRoute,
  SiteShopIndexRoute: SiteShopIndexRoute,
  SiteVergleichIndexRoute: SiteVergleichIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminAnfragenRoute: typeof AdminAnfragenRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminDruckplattenRoute: typeof AdminDruckplattenRoute
  AdminEinstellungenRoute: typeof AdminEinstellungenRoute
  AdminFilamenteRoute: typeof AdminFilamenteRoute
  AdminKalenderRoute: typeof AdminKalenderRoute
  AdminKalkulatorRoute: typeof AdminKalkulatorRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminTeileRoute: typeof AdminTeileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinanzenNeueRechnungRoute: typeof AdminFinanzenNeueRechnungRoute
  AdminKundenIdRoute: typeof AdminKundenIdRoute
  AdminWebsiteBestellungenRoute: typeof AdminWebsiteBestellungenRoute
  AdminWebsiteEinstellungenRoute: typeof AdminWebsiteEinstellungenRoute
  AdminWebsiteKundenRoute: typeof AdminWebsiteKundenRoute
  AdminAuftraegeIndexRoute: typeof AdminAuftraegeIndexRoute
  AdminFinanzenIndexRoute: typeof AdminFinanzenIndexRoute
  AdminKundenIndexRoute: typeof AdminKundenIndexRoute
  AdminAuftraegeIdPlattenRoute: typeof AdminAuftraegeIdPlattenRoute
  AdminFinanzenAbrechnungenIdRoute: typeof AdminFinanzenAbrechnungenIdRoute
  AdminShopBestellungenIdRoute: typeof AdminShopBestellungenIdRoute
  AdminAuftraegeIdIndexRoute: typeof AdminAuftraegeIdIndexRoute
  AdminFinanzenAbrechnungenIndexRoute: typeof AdminFinanzenAbrechnungenIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnfragenRoute: AdminAnfragenRoute,
  AdminChatRoute: AdminChatRoute,
  AdminDruckplattenRoute: AdminDruckplattenRoute,
  AdminEinstellungenRoute: AdminEinstellungenRoute,
  AdminFilamenteRoute: AdminFilamenteRoute,
  AdminKalenderRoute: AdminKalenderRoute,
  AdminKalkulatorRoute: AdminKalkulatorRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminTeileRoute: AdminTeileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinanzenNeueRechnungRoute: AdminFinanzenNeueRechnungRoute,
  AdminKundenIdRoute: AdminKundenIdRoute,
  AdminWebsiteBestellungenRoute: AdminWebsiteBestellungenRoute,
  AdminWebsiteEinstellungenRoute: AdminWebsiteEinstellungenRoute,
  AdminWebsiteKundenRoute: AdminWebsiteKundenRoute,
  AdminAuftraegeIndexRoute: AdminAuftraegeIndexRoute,
  AdminFinanzenIndexRoute: AdminFinanzenIndexRoute,
  AdminKundenIndexRoute: AdminKundenIndexRoute,
  AdminAuftraegeIdPlattenRoute: AdminAuftraegeIdPlattenRoute,
  AdminFinanzenAbrechnungenIdRoute: AdminFinanzenAbrechnungenIdRoute,
  AdminShopBestellungenIdRoute: AdminShopBestellungenIdRoute,
  AdminAuftraegeIdIndexRoute: AdminAuftraegeIdIndexRoute,
  AdminFinanzenAbrechnungenIndexRoute: AdminFinanzenAbrechnungenIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalBestellungenRoute: typeof PortalBestellungenRoute
  PortalDokumenteRoute: typeof PortalDokumenteRoute
  PortalPasswortRoute: typeof PortalPasswortRoute
  PortalProfilRoute: typeof PortalProfilRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBestellungenRoute: PortalBestellungenRoute,
  PortalDokumenteRoute: PortalDokumenteRoute,
  PortalPasswortRoute: PortalPasswortRoute,
  PortalProfilRoute: PortalProfilRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface WebsiteAdminRouteChildren {
  WebsiteAdminAnalyseRoute: typeof WebsiteAdminAnalyseRoute
  WebsiteAdminBlogRoute: typeof WebsiteAdminBlogRoute
  WebsiteAdminChatRoute: typeof WebsiteAdminChatRoute
  WebsiteAdminEinstellungenRoute: typeof WebsiteAdminEinstellungenRoute
  WebsiteAdminEquipmentRoute: typeof WebsiteAdminEquipmentRoute
  WebsiteAdminKundenRoute: typeof WebsiteAdminKundenRoute
  WebsiteAdminNavigationRoute: typeof WebsiteAdminNavigationRoute
  WebsiteAdminPartnerRoute: typeof WebsiteAdminPartnerRoute
  WebsiteAdminProjekteRoute: typeof WebsiteAdminProjekteRoute
  WebsiteAdminReviewsRoute: typeof WebsiteAdminReviewsRoute
  WebsiteAdminShopRoute: typeof WebsiteAdminShopRoute
  WebsiteAdminShopProdukteRoute: typeof WebsiteAdminShopProdukteRoute
  WebsiteAdminTeamRoute: typeof WebsiteAdminTeamRoute
  WebsiteAdminTimelineRoute: typeof WebsiteAdminTimelineRoute
  WebsiteAdminIndexRoute: typeof WebsiteAdminIndexRoute
  WebsiteAdminBestellungenIdRoute: typeof WebsiteAdminBestellungenIdRoute
  WebsiteAdminBestellungenIndexRoute: typeof WebsiteAdminBestellungenIndexRoute
}

const WebsiteAdminRouteChildren: WebsiteAdminRouteChildren = {
  WebsiteAdminAnalyseRoute: WebsiteAdminAnalyseRoute,
  WebsiteAdminBlogRoute: WebsiteAdminBlogRoute,
  WebsiteAdminChatRoute: WebsiteAdminChatRoute,
  WebsiteAdminEinstellungenRoute: WebsiteAdminEinstellungenRoute,
  WebsiteAdminEquipmentRoute: WebsiteAdminEquipmentRoute,
  WebsiteAdminKundenRoute: WebsiteAdminKundenRoute,
  WebsiteAdminNavigationRoute: WebsiteAdminNavigationRoute,
  WebsiteAdminPartnerRoute: WebsiteAdminPartnerRoute,
  WebsiteAdminProjekteRoute: WebsiteAdminProjekteRoute,
  WebsiteAdminReviewsRoute: WebsiteAdminReviewsRoute,
  WebsiteAdminShopRoute: WebsiteAdminShopRoute,
  WebsiteAdminShopProdukteRoute: WebsiteAdminShopProdukteRoute,
  WebsiteAdminTeamRoute: WebsiteAdminTeamRoute,
  WebsiteAdminTimelineRoute: WebsiteAdminTimelineRoute,
  WebsiteAdminIndexRoute: WebsiteAdminIndexRoute,
  WebsiteAdminBestellungenIdRoute: WebsiteAdminBestellungenIdRoute,
  WebsiteAdminBestellungenIndexRoute: WebsiteAdminBestellungenIndexRoute,
}

const WebsiteAdminRouteWithChildren = WebsiteAdminRoute._addFileChildren(
  WebsiteAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AnfragenRoute: AnfragenRoute,
  AnmeldenRoute: AnmeldenRoute,
  ChatRoute: ChatRoute,
  EinstellungenRoute: EinstellungenRoute,
  ErsatzteileRoute: ErsatzteileRoute,
  FilamenteRoute: FilamenteRoute,
  KalenderRoute: KalenderRoute,
  KalkulatorRoute: KalkulatorRoute,
  KleinserienRoute: KleinserienRoute,
  LoginRoute: LoginRoute,
  MeinKontoRoute: MeinKontoRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PortalRoute: PortalRouteWithChildren,
  ProfilErgaenzenRoute: ProfilErgaenzenRoute,
  ProfilVervollstaendigenRoute: ProfilVervollstaendigenRoute,
  PrototypenRoute: PrototypenRoute,
  RegistrierenRoute: RegistrierenRoute,
  TeileRoute: TeileRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  UploadsRoute: UploadsRoute,
  WebsiteAdminRoute: WebsiteAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuftraegeIdRoute: AuftraegeIdRoute,
  BewertungTokenRoute: BewertungTokenRoute,
  KundenIdRoute: KundenIdRoute,
  UploadTokenRoute: UploadTokenRoute,
  WebsiteSplatRoute: WebsiteSplatRoute,
  AuftraegeIndexRoute: AuftraegeIndexRoute,
  BewertungIndexRoute: BewertungIndexRoute,
  KundenIndexRoute: KundenIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
