// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-orders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.24.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-orders.ts
var list_orders_default = defineTool({
  name: "list_orders",
  title: "Auftr\xE4ge auflisten",
  description: "Listet Auftr\xE4ge (orders) auf, die dem angemeldeten Benutzer zug\xE4nglich sind. Optional nach Status oder Suchbegriff filtern.",
  inputSchema: {
    status: z.string().optional().describe("Optionaler Status-Filter, z. B. 'offen', 'in_produktion', 'geliefert'."),
    search: z.string().optional().describe("Suchbegriff f\xFCr Auftragsname oder Beschreibung."),
    limit: z.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht authentifiziert." }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select("id, name, beschreibung, status, datum, umsatz_total, lieferart, tracking_nr, customer_id, created_at").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`name.ilike.%${search}%,beschreibung.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.24.2";
var get_order_default = defineTool2({
  name: "get_order",
  title: "Auftrag im Detail",
  description: "Liefert einen einzelnen Auftrag inklusive Teile (parts) und Rechnungen (bills) anhand der Auftrags-ID.",
  inputSchema: {
    order_id: z2.string().describe("UUID des Auftrags.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht authentifiziert." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select("*").eq("id", order_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) {
      return { content: [{ type: "text", text: "Auftrag nicht gefunden oder kein Zugriff." }], isError: true };
    }
    const [{ data: parts }, { data: bills }] = await Promise.all([
      supabase.from("parts").select("*").eq("order_id", order_id),
      supabase.from("bills").select("*").eq("order_id", order_id)
    ]);
    const result = { order, parts: parts ?? [], bills: bills ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/search-customers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.24.2";
var search_customers_default = defineTool3({
  name: "search_customers",
  title: "Kunden suchen",
  description: "Sucht Kunden nach Name, Firma oder E-Mail. Nur Kunden, auf die der angemeldete Benutzer Zugriff hat.",
  inputSchema: {
    search: z3.string().optional().describe("Suchbegriff f\xFCr Name, Firma oder E-Mail."),
    limit: z3.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht authentifiziert." }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customers").select("id, name, vorname, firma, email, telefon, strasse, hausnummer, plz, ort, land, aktiv, created_at").order("created_at", { ascending: false }).limit(take);
    if (search) {
      query = query.or(`name.ilike.%${search}%,firma.ilike.%${search}%,email.ilike.%${search}%`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-bills.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.24.2";
var list_open_bills_default = defineTool4({
  name: "list_open_bills",
  title: "Offene Rechnungen",
  description: "Listet Rechnungen (bills) auf. Standardm\xE4ssig nur unbezahlte Rechnungen, sortiert nach F\xE4lligkeitsdatum.",
  inputSchema: {
    include_paid: z4.boolean().optional().describe("Wenn true, werden auch bezahlte Rechnungen zur\xFCckgegeben."),
    limit: z4.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_paid, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht authentifiziert." }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bills").select("id, order_id, rechnungsnummer, titel, betrag, faellig_am, bezahlt, bezahlt_am, empfaenger_name, empfaenger_firma, created_at").order("faellig_am", { ascending: true, nullsFirst: false }).limit(take);
    if (!include_paid) query = query.eq("bezahlt", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bills: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-inquiries.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.24.2";
var list_inquiries_default = defineTool5({
  name: "list_inquiries",
  title: "Anfragen auflisten",
  description: "Listet eingegangene Anfragen (inquiries) aus Kontaktformular, Kalkulator und Shop auf, optional nach Status gefiltert.",
  inputSchema: {
    status: z5.string().optional().describe("Optionaler Status-Filter, z. B. 'neu' oder 'erledigt'."),
    limit: z5.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht authentifiziert." }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("inquiries").select("id, name, email, telefon, betreff, nachricht, status, quelle, customer_id, order_id, created_at").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { inquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ukqtjdsjmtxgzhklvqky";
var mcp_default = defineMcp({
  name: "3dmuscio-dashboard",
  title: "3dMuscio Dashboard",
  version: "0.1.0",
  instructions: "Werkzeuge f\xFCr das 3DMuscio Dashboard (3D-Druckservice). Auftr\xE4ge, Kunden, Rechnungen und Anfragen lesen. Alle Zugriffe laufen als der angemeldete Benutzer mit dessen Berechtigungen.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_orders_default, get_order_default, search_customers_default, list_open_bills_default, list_inquiries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
